---
 - hosts: all
   become: true
   become_method: sudo
   vars:
    nodejs_ppa_script: 'curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -'
    ngrok_link : 'https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip'
    destination : "{{ lookup('env','APP_PATH') }}"
    username: "{{ lookup('env','GITHUB_USERNAME') }}"
    password: "{{ lookup('env','GITHUB_PASSWORD') }}"
    ngrok_port: "{{ lookup('env','NGROK_PORT') }}"
    config_path: "{{ lookup('env','CONFIG_PATH') }}"
    git_repo : 'https://{{username}}:{{password}}@github.ncsu.edu/adeshka/SE-Bot.git'
    setup_apt_1: 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
    setup_apt_2: 'gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9'
    setup_apt_3: 'gpg -a --export E084DAB9 | sudo apt-key add -'
    apt_update: 'apt-get update'
   tasks:
   - name: install python software properties
     apt:
       name: python-software-properties
       state: installed

   - name: add node.js ppa
     shell: "{{ nodejs_ppa_script }}"

   - name: install nodejs
     apt:
       name: nodejs
       state: installed

   - name: create nodejs link
     file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link

   - name: Install forever
     npm:
      name: forever
      global: yes

   - name: install git
     apt:
      name: git
      state: installed

   - name: Install ngrok
     npm:
      name: ngrok
      global: yes

   - name: Setup apt
     shell: "{{item}}"
     with_items:
         - "{{setup_apt_1}}"
         - "{{setup_apt_2}}"
         - "{{setup_apt_3}}"
         - "{{apt_update}}"

   - name: Install R
     apt:
         name: r-base
         state: installed

   - name: Add access permission to R-library directory
     file: path=/usr/local/lib/R/site-library mode=0777

   - name: Clone git repository
     git: repo="{{git_repo}}" dest="{{destination}}"

   - name: Export Configuration file
     copy: src="{{ config_path }}" dest="{{destination}}/config.json" force=yes

   - name: Add access permission to App
     file: path="{{destination}}" mode=0777 recurse=yes

   - name: Install R-dependencies
     shell: Rscript  "{{destination}}/lib/dependencies.R"

   - name: Install node modules
     npm: path="{{destination}}"

   - name: Install daemon
     apt:
        name: daemon
        state: installed

   - name: Run ngrok
     become: false
     shell: daemon -- ngrok http "{{ngrok_port}}"

   - name: Run app
     become: false
     shell: cd "{{destination}}" && forever start bin/www
